# specify the version of docker-compose
version: "3.8"

services:
  # define the frontend service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-app
    ports:
      - 5173:5173